# What is Pandas ?
## Pandas is a fast , powerful, flexible and easy to use open source data analysis and manipulation tool, built on top of the python programming language.

# Pandas Series?
## "Pandas Series is a one-dimensional labeled array capable of storing any data type and having an associated index."

## Series = Single Column Data
## DataFrame = Multiple Series ka collection.

In [1]:
import pandas as pd
import numpy as np

## Create Series using python list.

In [3]:
country = ["India", "Pakistan", "Srilanka", "USA"]
pd.Series(country)

0       India
1    Pakistan
2    Srilanka
3         USA
dtype: object

In [4]:
country[2]

'Srilanka'

In [9]:
batsman_run = [86,76,23,59,90]
pd.Series(batsman_run, dtype = 'int32')

0    86
1    76
2    23
3    59
4    90
dtype: int32

## Custom Index

In [14]:
marks = [56,78,45,90]
subjects = ['Science','English','Hindi','Maths']
pd.Series(marks, index =subjects)

Science    56
English    78
Hindi      45
Maths      90
dtype: int64

In [18]:
## Setting a Name
ad_marks = pd.Series(marks, index =subjects,name = "Adarsh's Marks")

In [19]:
ad_marks

Science    56
English    78
Hindi      45
Maths      90
Name: Adarsh's Marks, dtype: int64

## Create Series using dictionary

In [23]:
marks = {
    "Maths":90,
    "Hindi":78,
    "English": 87,
    "Science":67
}

marks_series = pd.Series(marks, name = "Adarsh's Marks")
marks_series

Maths      90
Hindi      78
English    87
Science    67
Name: Adarsh's Marks, dtype: int64

## Series Attributes

In [29]:
marks_series.index ## it shows us the indexes

Index(['Maths', 'Hindi', 'English', 'Science'], dtype='object')

In [30]:
marks_series.is_unique ## It tells us that our values are unique or not

True

In [32]:
marks_series.values ## it shows us the values in the form of numpy array

array([90, 78, 87, 67])

In [33]:
marks_series.ndim

1

In [36]:
marks_series.dtype

dtype('int64')

In [37]:
marks_series.name

"Adarsh's Marks"

In [38]:
marks_series.hasnans ## It tells us that we have nan value or not

False

In [40]:
marks_series.shape ## It tells us the shape

(4,)

In [41]:
marks_series.size ## It tells us total elements it stores

4

## Series using read_csv

In [48]:
df = pd.read_csv(r"C:\Users\adity\Downloads\subs.csv")

In [49]:
type(df)

pandas.core.frame.DataFrame

In [50]:
df

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [51]:
subs = df.squeeze("columns")

In [52]:
subs

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

## With 2 columns

In [55]:
df1 = pd.read_csv(r"C:\Users\adity\Downloads\kohli_ipl.csv", index_col= 'match_no')
type(df1)

pandas.core.frame.DataFrame

In [57]:
df1

          runs
match_no
1            1
2           23
3           13
4           12
5            1
...        ...
211          0
212         20
213         73
214         25
215          7

[215 rows x 1 columns]

In [59]:
runs = df1.squeeze()

In [60]:
runs

match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64

In [61]:
type(runs)

pandas.core.series.Series